### ISSUE TITLE
writeXKTModelToArrayBuffer throws invalid size error

### ISSUE THREAD

**Issue by intrida-dev** [xeokit/xeokit-convert#118]
We are using 'xeokit-convert' with version 1.1.9. We have our input json files which contain graphics + metadata information. Using these json files we create XKTModel and write it to the .xkt file. But for few of our json files, **writeXKTModelToArrayBuffer** gives following error:

![image](https://github.com/xeokit/xeokit-convert/assets/73640257/36642ea0-7795-4b0c-9621-bd88f1f41092)

We are providing the node.js script and the input json file, so you can reproduce this issue.

Use following command to execute the script.
**node "XKTCreator/XktCreator.js" "XKTCreator/Rachel Yu - PRS_5Mar2020.json" "XKTCreator/model.xkt" medium**

[XKTCreator.zip](https://github.com/xeokit/xeokit-convert/files/13317832/XKTCreator.zip)

[Rachel Yu - PRS_5Mar2020.zip](https://github.com/xeokit/xeokit-convert/files/13317870/Rachel.Yu.-.PRS_5Mar2020.zip)

Please use this file to reproduce the issue. And let us know, how can this be better handled.

**Comment by xeolabs** [comment]
We have a solution for this, I'll describe below. 

This happens when NodeJS cannot allocate all the necessary memory it needs to convert large files. NodeJS always has a hard 1GB limit on how much memory it can allocate for text strings in memory. When we try to process large glTF and JSON files, users often encounter the error you've shown. 

In xeokit-sdk 2.4.0 we can now avoid this error by using the model splitting feature described in [this tutorial](https://www.notion.so/xeokit/Automatically-Splitting-Large-Models-for-Better-Performance-165fc022e94742cf966ee50003572259).

For splitting, we extended [ifc2gltfcxconverter](https://github.com/a2e0005d00dc4f22b648f1237bc3245d?pvs=25) and convert2xkt, to automatically split models into parts, and we also extended xeokit-sdk and xeokit-bim-viewer to seamlessly load split models. Note that [ifc2gltfcxconverter](https://github.com/a2e0005d00dc4f22b648f1237bc3245d?pvs=25)  is our closed source tool provided by Creoox with a commercial license.

As a result, we are now able to convert and load models like this 2GB Baku stadium IFC, so it seems to solve this problem pretty nicely:

![Screenshot from 2023-11-10 02-00-29](https://github.com/xeokit/xeokit-convert/assets/83100/1786c0fa-598d-4b7c-b255-5eb446bf7480)

**Comment by xeolabs** [comment]
Unfortunately we can't help with the development of user's application code outside of a commercial support agreement, but hopefully this helps:

* Splitting has been only tested and documented by us for IFC files processed via `ifc2gltfcxconverter` 
* You could however still use the classes in `xeokit-convert` to build multiple `XKTModels` and serialize each of those to a separate XKT file, and generate a manifest file that lists those XKT files, so they can be loaded as a set into a xeokit viewer. We don't demonstrate that anywhere, but the classes are certainly usable like that.
* Splitting criteria - you could use the same criteria as `ifc2gltfcxconverter`, which is basically to output objects into a glTF until the glTF hits some specified size, eg 10MB, then save that glTF, start the next glTF, when that's got 10MB objects, save that, and so on.

**Comment by intrida-dev** [comment]
Thanks for you reply. This will help us in splitting large models.
